<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Controls\ComparserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\ExpressionControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\MenuControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\ParentControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\SettingsControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\ParentForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Controls\LogControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Forms\LineNumberControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Comparser\Gpu\" />
  </ItemGroup>

</Project>